const places={vienna:{latitude:48.2082,longitude:16.3738},bratislava:{latitude:48.1486,longitude:17.1077}};
const weatherCodes={0:['Klar','☀️'],1:['Überwiegend klar','🌤️'],2:['Teilweise bewölkt','⛅'],3:['Bewölkt','☁️'],45:['Nebel','🌫️'],48:['Raureifnebel','🌫️'],51:['Leichter Nieselregen','🌦️'],53:['Nieselregen','🌦️'],55:['Starker Nieselregen','🌧️'],61:['Leichter Regen','🌦️'],63:['Regen','🌧️'],65:['Starker Regen','🌧️'],71:['Leichter Schneefall','🌨️'],73:['Schneefall','🌨️'],75:['Starker Schneefall','🌨️'],80:['Leichte Schauer','🌦️'],81:['Regenschauer','🌧️'],82:['Starke Schauer','⛈️'],95:['Gewitter','⛈️'],96:['Gewitter mit Hagel','⛈️'],99:['Starkes Gewitter','⛈️']};
const TOUR_START=new Date('2026-09-24T13:00:00+02:00');
const TOUR_END=new Date('2026-09-25T16:00:00+02:00');

function description(code){return weatherCodes[code]||['Unbekannt','🌡️']}
function endpoint({latitude,longitude}){const p=new URLSearchParams({latitude,longitude,current:'temperature_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m',hourly:'temperature_2m,precipitation_probability,weather_code,wind_speed_10m,wind_gusts_10m',timezone:'Europe/Vienna',forecast_days:'7'});return `https://api.open-meteo.com/v1/forecast?${p}`}
async function loadPlace(id){const response=await fetch(endpoint(places[id]));if(!response.ok)throw new Error('Wetterdienst nicht erreichbar');const data=await response.json();renderCurrent(id,data.current);return data}
function renderCurrent(id,current){const card=document.getElementById(id);const [label,icon]=description(current.weather_code);card.querySelector('.weather-icon').textContent=icon;card.querySelector('.temperature').textContent=`${Math.round(current.temperature_2m)}°`;card.querySelector('.condition').textContent=label;card.querySelector('[data-field="wind"]').textContent=`${Math.round(current.wind_speed_10m)} km/h`;card.querySelector('[data-field="rain"]').textContent=`${current.precipitation.toFixed(1)} mm`;card.querySelector('[data-field="feels"]').textContent=`${Math.round(current.apparent_temperature)}°`;card.classList.remove('skeleton')}
function tourHours(data){return data.hourly.time.map((time,i)=>({time:new Date(time),temp:data.hourly.temperature_2m[i],rain:data.hourly.precipitation_probability[i],code:data.hourly.weather_code[i],wind:data.hourly.wind_speed_10m[i],gust:data.hourly.wind_gusts_10m[i]})).filter(x=>x.time>=TOUR_START&&x.time<=TOUR_END)}
function sampleHours(hours){const targets=['2026-09-24T13:00','2026-09-24T17:00','2026-09-25T09:00','2026-09-25T15:00'].map(x=>new Date(`${x}:00+02:00`).getTime());return targets.map(t=>hours.reduce((a,b)=>Math.abs(b.time-t)<Math.abs(a.time-t)?b:a))}
function renderForecast(data){const hours=tourHours(data);const box=document.getElementById('forecast');if(!hours.length){box.innerHTML='<p>Die Stundenprognose ist noch nicht verfügbar. Open-Meteo stellt sie näher am Tourtermin automatisch bereit.</p>';return []}box.innerHTML=sampleHours(hours).map(h=>{const [label,icon]=description(h.code);return `<article class="forecast-item"><span class="time">${new Intl.DateTimeFormat('de-AT',{weekday:'short',hour:'2-digit',minute:'2-digit'}).format(h.time)}</span><div class="icon">${icon}</div><strong>${Math.round(h.temp)} °C</strong><small>${label}<br>Regen ${h.rain}% · Wind ${Math.round(h.wind)} km/h</small></article>`}).join('');return hours}
function renderAdvice(hours){if(!hours.length)return;const maxRain=Math.max(...hours.map(x=>x.rain));const maxGust=Math.max(...hours.map(x=>x.gust));let text='Gute Bedingungen: Aktuell sind weder viel Regen noch starke Böen erkennbar.';if(maxRain>=60&&maxGust>=45)text='Vorsicht: Erhöhtes Regenrisiko und kräftige Böen. Regenausrüstung einpacken und Prognose kurz vor Abfahrt prüfen.';else if(maxRain>=60)text='Regen wahrscheinlich: Regenjacke, Überschuhe und wasserdichte Gepäckhüllen einplanen.';else if(maxGust>=45)text='Kräftige Böen möglich: Besonders auf offenen Abschnitten entlang der Donau vorsichtig fahren.';document.getElementById('advice-text').textContent=text}
async function refresh(){const button=document.getElementById('refresh');button.disabled=true;document.getElementById('notice').hidden=true;try{const [vienna,bratislava]=await Promise.all([loadPlace('vienna'),loadPlace('bratislava')]);const hours=renderForecast(bratislava);renderAdvice(hours);document.getElementById('updated').textContent=`Zuletzt aktualisiert: ${new Intl.DateTimeFormat('de-AT',{dateStyle:'short',timeStyle:'short'}).format(new Date())}`}catch(error){const notice=document.getElementById('notice');notice.textContent='Die Live-Daten konnten gerade nicht geladen werden. Bitte später erneut versuchen.';notice.hidden=false}finally{button.disabled=false}}
document.getElementById('refresh').addEventListener('click',refresh);refresh();setInterval(refresh,15*60*1000);
